### ISSUE TITLE
Quota error

### ISSUE THREAD

**Issue by fimdomeio** [yasyf/gpt-do#2]
I'm receiving `openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.`

Either this is a block from openai on this prompt or something else, but I didn't exceeded the quota (only have been using chatgpt for one or to questions a day) and I do have credits on a business account.

**Comment by yasyf** [comment]
weird, I will investigate

**Comment by yasyf** [comment]
@fimdomeio I'm not able to repro this. The default model used is GPT3, _not_ ChatGPT. Is your billing set up properly for GPT3?

**Comment by robbiebowman** [comment]
I'm encountering the same issue. I'm using a key generated on https://beta.openai.com/account/api-keys

Admittedly I'm on a personal/unpaid account. Not sure if that precludes me from this app.

**Comment by yasyf** [comment]
@robbiebowman I haven't tested with an unpaid account, but my guess is for some reason they're not allowing this prompt/a prompt of this length unless you pay.

**Comment by robbiebowman** [comment]
> @robbiebowman I haven't tested with an unpaid account, but my guess is for some reason they're not allowing this prompt/a prompt of this length unless you pay.

Just tried adding billing information. Now it all works as expected. 👍

**Comment by yasyf** [comment]
cool, closing this then!

**Comment by fimdomeio** [comment]
Just to confirm that it's also working for me now. I believe there's a delay between setting up a paid account and the quota exceeded message to disapear.
