### ISSUE TITLE
FR: confirm with one keypress

### ISSUE THREAD

**Issue by chrisgrieser** [yasyf/gpt-do#4]
Hi, thanks for the nice tool.

I was wondering whether you could make it that the confirmation prompt accepts just on keypress, essentially only "y" or "n" instead of "y+return" or "n+return". 

With shell script, you can get this behavior with `read -k`, but unfortunately I do not know how to do this with python (otherwise I would have made a PR myself).

**Comment by yasyf** [comment]
This should be fixed in `0.1.16`! Can you confirm?

**Comment by chrisgrieser** [comment]
can confirm, it works :)
Thanks!
